import { ICartDelivery } from "./localization";

export const cartDeliveryTextEn: ICartDelivery = {
	city: 'Your city',
	deliveryMethod: {
		delivery: {
			method: 'Delivery',
			date: 'Data',
			time: 'Time',
			timePlasholder: 'Choose delivery time',
			price: 'free',
			street: 'Street, house/corps',
			flat: 'flat',
			comment: 'Commentary to the courier',
		},
		pickup: {
			method: 'Pickup',
			productIsAvailable: ['The goods are available in ', 'stores',],
			btnNext: 'Show more',
			shope: [{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '1', },
			{ city: 'Hamburg', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '2', },
			{ city: 'Berlin', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '3', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '4', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '5', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '6', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '7', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '8', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '9', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '10', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '11', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '12', },
			{ city: 'Hamburg', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '13', },
			{ city: 'Berlin', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '14', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '15', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '16', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '17', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '18', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '19', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '20', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '21', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '22', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '23', },
			],
		},
	},
};

export const cartDeliveryTextUa: ICartDelivery = {
	city: 'Ваше місто',
	deliveryMethod: {
		delivery: {
			method: 'Доставка',
			date: 'Дата',
			time: 'Час',
			timePlasholder: 'Оберить час доставки',
			price: 'бескоштовно',
			street: 'Вулиця, будинок/корпус',
			flat: 'Квартира',
			comment: "Rоментар кур'єру"
		},
		pickup: {
			method: 'Самовивіз',
			productIsAvailable: ['Товар доступений у ', 'магазинах',],
			btnNext: 'Показати ще',
			shope: [{ city: 'Berlin', adress: 'проспект Миру, 78', mode: 'ПН-НД 09:00 — 22:00', idShop: '1', },
			{ city: 'Hamburg', adress: 'вулица Вишнева, 35 к.2', mode: 'ПН-НД 09:00 — 22:00', idShop: '2', },
			{ city: 'Berlin', adress: 'проспект Перемоги, 44', mode: 'ПН-НД 09:00 — 22:00', idShop: '3', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '4', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '5', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '6', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '7', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '8', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '9', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '10', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '11', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '12', },
			{ city: 'Hamburg', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '13', },
			{ city: 'Berlin', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '14', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '15', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '16', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '17', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '18', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '19', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '20', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '21', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '22', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '23', },
			],
		},
	},
};

export const cartDeliveryTextRu: ICartDelivery = {
	city: 'Ваш город',
	deliveryMethod: {
		delivery: {
			method: 'Доставка',
			date: 'Дата',
			time: 'Время',
			timePlasholder: 'Выберите время доставки',
			price: 'бесплатно',
			street: 'Улица, дом/корпус',
			flat: 'Квартира',
			comment: 'Комментарий курьеру',
		},
		pickup: {
			method: 'Самовывоз',
			productIsAvailable: ['Товар доступен в ', 'магазинах',],
			btnNext: 'Показать еще',
			shope: [{ city: 'Berlin', adress: ' проспект Мира, 78', mode: 'ПН-ВС 09:00 — 22:00', idShop: '1', },
			{ city: 'Hamburg', adress: 'улица Вишневая, 35 к.2', mode: 'ПН-ВС 09:00 — 22:00', idShop: '2', },
			{ city: 'Berlin', adress: ' проспект Победы, 44', mode: 'ПН-ВС 09:00 — 22:00', idShop: '3', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '4', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '5', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '6', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '7', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '8', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '9', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '10', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '11', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '12', },
			{ city: 'Hamburg', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '13', },
			{ city: 'Berlin', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '14', },
			{ city: 'Berlin', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '15', },
			{ city: 'Köln', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '16', },
			{ city: 'Frankfurt am Main', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '17', },
			{ city: 'Köln', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '18', },
			{ city: 'Leipzig', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '19', },
			{ city: 'Hannover', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '20', },
			{ city: 'Leipzig', adress: 'Miru avenue , 78', mode: 'MN-SN 09:00 — 22:00', idShop: '21', },
			{ city: 'Frankfurt am Main', adress: 'Vishneva street, 35 k.2', mode: 'MN-SN 09:00 — 22:00', idShop: '22', },
			{ city: 'Bremen', adress: 'Peremogy avenue, 44', mode: 'MN-SN 09:00 — 22:00', idShop: '23', },
			],
		},
	},
};
